### ISSUE TITLE
Changes are not pushed to gitolite-admin if merge conflicts between head and remote

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/Java-Gitolite-Manager#20]
Changes are not pushed to gitolite-admin if merge conflicts between head and remote

**Comment by michaeldejong** [comment]
Since resolving merge conflicts is probably too hard, we should discard all changes from our repo (either hard resetting, or dropping the repo and re-cloning it even), and then re-run all the actions on the queue.

Should be a nice one to fix :smile:

**Comment by JWGmeligMeyling** [comment]
What is really strange here is that JGit push should throw an exception if its behind the remote and can't pull (at least thats what I expect). This exception is never thrown, so the config finishes to apply and both the gitolite manager and the git server think the changes are applied properly.

So first we should find out why the push didnt throw, maybe this was a bug in an older Jgit version, or does the command return a special return value if the push failed.

From there it would indeed be nice to fetch the new config and applying the changes on that commit.
